import Head from 'next/head';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { CacheProvider } from '@emotion/react';
import createEmotionCache from '../styles/createEmotionCache';
import Header from '../components/header'
import "/styles/globals.css";
import theme from '../styles/theme';
import AppProvider from '../components/general/AppProviders';
import { AppWrapper } from '../Context/state';
const clientSideEmotionCache = createEmotionCache();

export default function MyApp(props) {
  const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;

  return (
    <AppProvider pageProps={pageProps}>
      <CacheProvider value={emotionCache}>
        <AppWrapper>
        <Head>
          <title>Devon Owen</title>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ThemeProvider theme={theme}>
          {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
          <CssBaseline />
          <Header/>
          <Component {...pageProps} />
        </ThemeProvider>
        </AppWrapper>
      </CacheProvider>
    </AppProvider>
  );
}